### PR TITLE
Implement TreatTags

### PR DESCRIPTION
**Pull request by murribu**
I wanted some way to control incoming html. This was an attempt to do that. Please see the notes in /src/Wysiwyg/Modifier/TreatTags.php for more details.

### CODE REVIEW

**Comment by MarceauKa** [comment]
Hi and thank you for your PR!
Let me the time to check your changes.

**Comment by murribu** [comment]
Your welcome! I hope it's useful - and consistent with what this package is attempting to accomplish. If not, no big deal - just thought I'd offer it. Let me know if you have any questions.

**Comment by MarceauKa** [comment]
Finally reverted, sorry :(

1. Tests are not complete.
2. TreatTags does a lot (inserting attributes and checking attributes). Consider both to be separate modifiers.
3. There's a bug. If the input is by default wrapped in a tag, modifier can goes wrong.
4. Options are a bit complex, I see something like this:
```php
'tags' => [
    'a' => ['href', 'title'],
    'p'
    'br',
]
```

We can imagine an integration of HTMLPurifier.

**Comment by murribu** [comment]
No problem. Thanks for the feedback.
Yeah, I looked at HTMLPurifier - perhaps that's closer to what I was looking for.
I'll probably just leave TreatTags alone for now.

Thanks again for the consideration!

**Pull request merged**
